// <auto-generated />
namespace Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FK_Obrigatorias : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FK_Obrigatorias));
        
        string IMigrationMetadata.Id
        {
            get { return "201606190035497_FK_Obrigatorias"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
